<a href="https://colab.research.google.com/github/Hamza-t/Tensorflow-workshop/blob/main/00_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Resume
##Introduction to TensorFlow
https://www.tensorflow.org/api_docs/python/ 

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # find the version number (should be 2.x+)

2.8.2


In [ ]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
scalar.ndim,vector.ndim,matrix.ndim,tensor.ndim

(0, 1, 2, 3)

In [ ]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Won't error /: To change an element of a tf.Variable() tensor requires the assign() method.
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Create random tensor
random = tf.random.Generator.from_seed(42)
random = random.normal(shape=(3, 2))
random

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
print(tf.random.shuffle(not_shuffled))
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# Make a tensor of all ones
tf.ones(shape=(3, 2))
# Make a tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
#the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])

# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([-1, -7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -7], dtype=int32)>)

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
C = tf.abs(C)
B, C

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:

* tf.reduce_min() - find the minimum value in a tensor.
* tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* tf.reduce_mean() - find the mean of all elements in a tensor.
* tf.reduce_sum() - find the sum of all elements in a tensor.
* tf.argmax() - find the position of the maximum element in a given tensor.
* tf.argmin() - find the position of the minimum element in a given tensor.

If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().
* tf.squeeze() - remove all dimensions of 1 from a tensor.

Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:

* tf.square() - get the square of every value in a tensor.
* tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
* tf.math.log() - get the natural log of every value in a tensor (elements need to floats).

Tensors created with tf.Variable() can be changed in place using methods such as:

* .assign() - assign a different value to a particular index of a variable tensor.
* .add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.

Tensors can also be converted to NumPy arrays using:

* np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).
* tensor.numpy() - call on a tensor to convert to an ndarray.

* If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().

You should also specify the depth parameter (the level which you want to one-hot encode to).

 In the **@tf.function** decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with **@tf.function**, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (***by making it part of a computation graph***).

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
!nvidia-smi

Sat Sep 17 11:14:13 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    30W /  70W |    286MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#🛠 Exercises


In [ ]:
#Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
scalar = tf.constant(3)
vector = tf.constant([1, 3])
matrix = tf.constant([[1,2],[1,2]])
tensor = tf.ones([2,2,3])

In [ ]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
#Find the shape, rank and size of the tensors you created in 1.

print("Shape of tensor:", tensor.shape)
print("Number of dimensions (rank):", tensor.ndim)
print("Total number of elements (2*3*4*5):", tf.size(tensor).numpy())

Shape of tensor: (2, 2, 3)
Number of dimensions (rank): 3
Total number of elements (2*3*4*5): 12


In [ ]:
#Create two tensors containing random values between 0 and 1 with shape [5, 300]

random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.uniform(shape=(5, 300))

random_2 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_2 = random_2.uniform(shape=(5, 300))


In [ ]:
random_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, ..., 0.5816356 , 0.5627874 ,
        0.7491298 ],
       [0.6438937 , 0.6938418 , 0.04408407, ..., 0.04825139, 0.5099728 ,
        0.26470542],
       [0.21373153, 0.6683699 , 0.78474844, ..., 0.19658887, 0.22030771,
        0.3766911 ],
       [0.68190825, 0.29304636, 0.5415933 , ..., 0.37111604, 0.76053166,
        0.7538099 ],
       [0.8011551 , 0.48830473, 0.13867617, ..., 0.20301867, 0.8378159 ,
        0.19984365]], dtype=float32)>

In [ ]:
#Multiply the two tensors you created in 3 using matrix multiplication.
new_1 = random_1*3
new_2 = random_2*3
#Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tf.transpose(new_1), new_2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[19.157816, 15.586949,  9.139173, ...,  8.321833, 17.883091,
        13.377998],
       [15.586949, 16.1423  , 10.0282  , ...,  7.205622, 13.923589,
        11.744939],
       [ 9.139173, 10.0282  , 10.214192, ...,  5.837635,  8.802045,
         9.738777],
       ...,
       [ 8.321833,  7.205622,  5.837635, ...,  5.023971,  7.628327,
         7.585823],
       [17.883091, 13.923589,  8.802045, ...,  7.628327, 17.151133,
        12.422788],
       [13.377998, 11.744939,  9.738777, ...,  7.585823, 12.422788,
        12.431947]], dtype=float32)>

In [ ]:
#Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
random_1 = tf.random.Generator.from_seed(5) # set the seed for reproducibility
random_1 = random_1.uniform(shape=(224, 224, 3))



#Find the min and max values of the tensor you created in 6.
print(tf.reduce_min(random_1))
print(tf.reduce_max(random_1))

tf.Tensor(4.053116e-06, shape=(), dtype=float32)
tf.Tensor(0.99998736, shape=(), dtype=float32)


'\nCreated a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].\nCreate a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.\nOne-hot encode the tensor you created in 9.\n'

In [ ]:
#Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
import numpy as np
G = tf.constant(np.random.randint(0, 100,150528), shape=(1, 224, 224, 3))
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([224, 224, 3])

In [ ]:
#Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
F = tf.constant(np.random.random(10))
print(F.numpy())
#One-hot encode the tensor F.
tf.one_hot(F.numpy(), depth=10)

[0.99459388 0.39920925 0.6749336  0.14683303 0.19144101 0.57306856
 0.82785343 0.32163734 0.87554912 0.98910409]


<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#end!